import type { NextPage } from "next";
import Head from "next/head";
import { TypedTransComponent } from "../i18n/components/TypedTransComponent";
import { useTypedTranslation } from "../i18n/hooks";
import { initI18n } from "../services/localization/i18n";
import styles from "../styles/Home.module.css";
import { nameSpaces } from "../translations";

initI18n();

const Home: NextPage = () => {
  const { t } = useTypedTranslation(nameSpaces.auth);
  return (
    <div className={styles.container}>
      <Head>
        <title>
          <div>{t("appName", { ns: nameSpaces.common })}</div>
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <TypedTransComponent
            i18nKey="signin.header"
            ns={nameSpaces.auth}
            components={{
              Link: <a href="https://github.com/Ar-mane/typed-i18next" />,
            }}
          />
        </h1>

        <div className={styles.grid}>
          <div>{t("signin.hint")}</div>
          <TypedTransComponent
            i18nKey="signin.term&policy"
            ns={nameSpaces.auth}
            components={{
              signed: (
                <a
                  style={{ textDecoration: "underline" }}
                  href="https://github.com/Ar-mane/typed-i18next"
                />
              ),
            }}
          />
          <button>{t("signin.signinButton")}</button>
        </div>
      </main>
    </div>
  );
};

export default Home;
